### ISSUE TITLE
dev-lang/v8 is gone from the tree

### ISSUE THREAD

**Issue by hasufell** [desura/desurium-overlay#1]
it has to be bundled.

**Comment by karolherbst** [comment]
yeah, the fix should be pretty simple
- remove v8 from deb
- remove froce-sys-deps cmake options to let desurium build it's v8

maybe we should add ab option to handle v8 like wxGTK, but this is currently "the best way around it"

**Comment by hasufell** [comment]
> maybe we should add ab option to handle v8 like wxGTK

yes
